version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    ports:
      - "3000:3000"
      - "3001:3001"
      - "6006:6006" # For Storybook if used
    environment:
      - NODE_ENV=development