# Docker Compose configuration for MCP Router

version: '3.8'

services:
  frontend:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile
      target: frontend-runtime
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    volumes:
      - ../../packages/frontend/src:/app/packages/frontend/src:ro
      - ../../packages/shared/src:/app/packages/shared/src:ro
      - ../../packages/frontend/public:/app/packages/frontend/public:ro

  backend:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile
      target: backend-runtime
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mcp_router
      - PORT=8000
      - DEBUG=true
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    volumes:
      - ../../packages/backend/src:/app/packages/backend/src:ro
      - ../../packages/shared/src:/app/packages/shared/src:ro
    command: >
      sh -c "python -m alembic upgrade head &&
             python -m uvicorn packages.backend.src.api.main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mcp_router
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mcp_router"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

networks:
  mcp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
          gateway: 192.168.90.1

volumes:
  postgres_data:
  redis_data: 