name: CI/CD Pipeline for MCP Router

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'screenshots/**'
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'screenshots/**'

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          
      - name: Install root dependencies
        run: npm ci
        
      - name: Install package dependencies
        run: |
          npm run fix-imports
          cd packages/shared && npm ci && cd ../..
          cd packages/frontend && npm ci && cd ../..
          cd packages/backend && npm ci && cd ../..
          
      - name: Check circular dependencies
        run: node scripts/check-circular-deps.js
        
      - name: Lint shared package
        run: cd packages/shared && npm run lint && cd ../..
        
      - name: Lint frontend package
        run: cd packages/frontend && npm run lint && cd ../..
        
      - name: Lint backend package
        run: cd packages/backend && npm run lint && cd ../..

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mcp_router_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: '**/requirements.txt'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev python3-dev gcc libjpeg-dev zlib1g-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r packages/backend/requirements.txt
        pip install pytest-cov pytest-asyncio

    - name: Install Node.js dependencies
      run: |
        npm ci
        cd packages/shared && npm ci && cd ../..
        cd packages/frontend && npm ci && cd ../..
        cd packages/backend && npm ci && cd ../..

    - name: Build shared package
      run: |
        cd packages/shared && npm run build && cd ../..

    - name: Run shared tests
      run: |
        cd packages/shared && npm test && cd ../..

    - name: Run backend tests
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/mcp_router_test
        REDIS_URL: redis://localhost:6379/0
      run: |
        pytest tests/ --cov=packages/backend --cov-report=xml

    - name: Run frontend tests
      run: |
        cd packages/frontend && npm test -- --coverage && cd ../..

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml,./packages/frontend/coverage/coverage-final.json

  build:
    name: Build Images
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set environment suffix
      id: set-suffix
      run: |
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          echo "ENV_SUFFIX=prod" >> $GITHUB_OUTPUT
        else
          echo "ENV_SUFFIX=dev" >> $GITHUB_OUTPUT
        fi

    - name: Build and push backend
      uses: docker/build-push-action@v4
      with:
        context: .
        file: infra/docker/Dockerfile
        target: backend-runtime
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
          ghcr.io/${{ github.repository }}/backend:${{ steps.set-suffix.outputs.ENV_SUFFIX }}
          ${{ github.ref == 'refs/heads/main' && 'ghcr.io/${{ github.repository }}/backend:latest' || '' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          NODE_ENV=${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    - name: Build and push frontend
      uses: docker/build-push-action@v4
      with:
        context: .
        file: infra/docker/Dockerfile
        target: frontend-runtime
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}
          ghcr.io/${{ github.repository }}/frontend:${{ steps.set-suffix.outputs.ENV_SUFFIX }}
          ${{ github.ref == 'refs/heads/main' && 'ghcr.io/${{ github.repository }}/frontend:latest' || '' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          NODE_ENV=${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

  deploy-dev:
    name: Deploy to Development
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Kubectl
      uses: azure/setup-kubectl@v3
      
    - name: Deploy to development environment
      run: |
        echo "Deploying MCP Router to development environment"
        # Update k8s manifests with the new image tag
        sed -i 's|image: ghcr.io/${{ github.repository }}/backend:.*|image: ghcr.io/${{ github.repository }}/backend:${{ github.sha }}|' infra/k8s/dev/backend-deployment.yaml
        sed -i 's|image: ghcr.io/${{ github.repository }}/frontend:.*|image: ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}|' infra/k8s/dev/frontend-deployment.yaml
        
        # Apply k8s manifests
        # kubectl apply -f infra/k8s/dev/

  deploy-prod:
    name: Deploy to Production
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Kubectl
      uses: azure/setup-kubectl@v3
      
    - name: Deploy to production environment
      run: |
        echo "Deploying MCP Router to production environment"
        # Update k8s manifests with the new image tag
        sed -i 's|image: ghcr.io/${{ github.repository }}/backend:.*|image: ghcr.io/${{ github.repository }}/backend:${{ github.sha }}|' infra/k8s/prod/backend-deployment.yaml
        sed -i 's|image: ghcr.io/${{ github.repository }}/frontend:.*|image: ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}|' infra/k8s/prod/frontend-deployment.yaml
        
        # Apply k8s manifests
        # kubectl apply -f infra/k8s/prod/ 